baseURL = 'https://infoops.fr/'
languageCode = 'fr'
DefaultContentLanguage = "fr"
title = 'Info Ops France'
theme = 'chalk'
paginate = '25'

[params]
  dateFormat = "02 Jan 2006"

[params.chalk]
  about_enabled = 'true'
  scrollappear_enabled = 'true'
  theme_toggle = 'true'
  blog_theme = 'light'
  tag_nav_enabled = 'true'

[params.social]
  twitter = 'infoopsfr'
  email = 'contact@infoops.fr'