baseURL: "/"
languageCode: "fr"
DefaultContentLanguage: "fr"
title: "Info Ops France"
theme: "hugo-theme-novela"
pygmentsstyle: 'monokai'
paginate: 6
enableRobotsTXT: true
canonifyURLs: true


social:
  twitter: "https://twitter.com/infoopsfr"
  facebook: "#"
  linkedin: "#"
  youtube: "#"
  
taxonomies:
          tag: "tags"
          author: "authors"
          preserveTaxonomyNames: true
