baseURL = 'https://infoops.fr'
languageCode = 'fr'
DefaultContentLanguage = "fr"
title = 'Info Ops France'
theme = 'lanyon-hugo'
paginate = '5'

[Author]
   name = 'Rédaction'

[Taxonomies]
   tag = "tags"
   categories = "categories"

[Params]
   title = "Info Ops France"
   dateFormat = "Monday, Jan 2, 2006"
   mainSections = "post"