baseURL = "https://infoops.fr"
locale = "fr"
defaultContentLanguage = "fr"
title = "Info Ops France"
summaryLength = 40
enableEmoji = false
# Français : pas de Title Case sur les titres de listes/taxonomies.
capitalizeListTitles = false

[pagination]
  pagerSize = 4

[taxonomies]
  tag = "tags"
  series = "series"

[[menu.main]]
  name = "Accueil"
  weight = 10
  identifier = "accueil"
  url = "/"
[[menu.main]]
  name = "Archive"
  weight = 20
  identifier = "archive"
  url = "/posts/"
[[menu.main]]
  name = "Séries"
  weight = 25
  identifier = "series"
  url = "/series/"
[[menu.main]]
  name = "Tags"
  weight = 30
  identifier = "tags"
  url = "/tags/"
[[menu.main]]
  name = "Recherche"
  weight = 35
  identifier = "recherche"
  url = "/recherche/"
[[menu.main]]
  name = "À propos"
  weight = 40
  identifier = "a-propos"
  url = "/a-propos/"

[params]
  author = "Denys Kolesnyk"
  subTitle = "« L'esprit des nations belligérantes est la 4ème dimension [de la guerre] »"
  keywords = ["Info Ops France","désinformation","infoguerre"]
  description = "L’initiative Info Ops France a pour but d’améliorer la résilience informationnelle de la société française."
  enableMathJax = false
  enableSummary = true
  mainSections = ["posts","post"]

  [params.social]
    twitter = "https://twitter.com/infoopsfr"
    facebook = "https://www.facebook.com/infoopsfr/"

[markup]
  [markup.goldmark.renderer]
    unsafe = true
  [markup.highlight]
    noClasses = false
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 3
