baseURL = '/'
languageCode = 'fr-fr'
title = 'Info Ops France'
theme = 'chalk'
paginate = '25'

[params.chalk]
  about_enabled = 'true'
  scrollappear_enabled = 'true'
  theme_toggle = 'true'
  blog_theme = 'light'
  tag_nav_enabled = 'true'

[params.social]
  twitter = 'infoopsfr'
  email = 'mailto:contact@infoops.fr'