baseURL = 'https://infoops.fr/'
languageCode = 'fr'
DefaultContentLanguage = "fr"
title = 'Info Ops France'
theme = "tale-hugo"
paginate = '5'

[Author]
    name = "Info Ops France"

[Taxonomies]
   tag = "tags"
   categories = "categories"

[menu]
  [[menu.main]]
    identifier = "À propos"
    name = "À propos"
    title = "À propos"
    url = "/a-propos/"
    weight = 1
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    title = "Posts"
    url = "/posts/"
    weight = 0