baseURL = 'https://infoops.fr/'
languageCode = 'fr'
DefaultContentLanguage = "fr"
title = 'Info Ops France'
theme = 'chalk'
paginate = '25'
TimeZone = 'Europe/Paris'

[params]
  DateForm = "2.1.2006"

[params.chalk]
  about_enabled = 'true'
  scrollappear_enabled = 'true'
  theme_toggle = 'true'
  blog_theme = 'light'
  tag_nav_enabled = 'true'

[params.social]
  twitter = 'infoopsfr'
  email = 'contact@infoops.fr'